<Project Sdk="Microsoft.NET.Sdk.Worker">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>disable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>dotnet-EMLWorker-cf1387db-8d08-4d95-92a6-ef797589fe8c</UserSecretsId>
	<CETCompat>false</CETCompat>

	<AssemblyTitle>Mail2EInvoice</AssemblyTitle>
	<Product>Mail2EInvoice</Product>
	<Company>Inbox concept Systemhaus GmbH</Company>
	<Authors>Jens Krieger</Authors>

	<Version>1.0.0</Version>
	<AssemblyVersion>1.0.0.0</AssemblyVersion>
	<FileVersion>1.0.0.0</FileVersion>

	<Description>Verarbeitet E-Mails und bereitet Anghänge zur Weiterverarbeitung auf.</Description>
	<Copyright>© 2026 Inbox concept Systemhaus GmbH</Copyright>
  </PropertyGroup>

  <ItemGroup>
	<None Include="ChromeHeadlessShell\**">
	  <CopyToOutputDirectory>Always</CopyToOutputDirectory>
	</None>
  </ItemGroup>

  <ItemGroup>
	<None Include="Runtime\**">
	  <CopyToOutputDirectory>Always</CopyToOutputDirectory>
	</None>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.12" />
    <PackageReference Include="Microsoft.Extensions.Hosting.WindowsServices" Version="10.0.12" />
    <PackageReference Include="MimeKit" Version="4.18.1" />
    <PackageReference Include="PDFsharp" Version="6.2.4" />
    <PackageReference Include="PuppeteerSharp" Version="25.12.0" />
    <PackageReference Include="Serilog" Version="4.4.0" />
    <PackageReference Include="Serilog.Extensions.Logging" Version="10.0.0" />
    <PackageReference Include="Serilog.Sinks.File" Version="7.0.0" />
  </ItemGroup>

  <ItemGroup>
    <None Update="Default.pdf">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="README.md">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>
</Project>
